org: elanwy
app: aws-node-http-api-application
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_PROCESSED_IMAGE_LABEL_TABLE: ${self:service}-processedImageLabelTable-${sls:stage}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource:
          - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-processedImageLabelTable-${sls:stage}
        - Effect: 'Allow'
          Action:
            - s3:*
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "rekognition:*"
          Resource: "*"
functions:
#  Lambda functions
  imageAnalysis:
    handler: imageAnalysis.imageAnalysis
    events:
      - http:
          path: analysis
          method: post
  uploadFile:
    handler: uploadFile.uploadFile
    events:
      - http:
          method: post
          path: upload
          cors: true

resources:
  Resources:
    DrivingLicencePhotosBucket:
#      S3 allows storage of media files, like a file storage system on a computer
      Type: AWS::S3::Bucket
      Properties:
        BucketName: drivinglicencephotostoanalyse
#        stores queryable data
    ProcessedImageLabelTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-processedImageLabelTable-${sls:stage}